### ISSUE TITLE
Todo App

### ISSUE THREAD

**Issue by nithinkr1shna** [14Sarah/Todo_app#3]
## Iteration  1

- [ ] Create an Input box
- [ ] Add a button to the side of the input box.
- [ ] Add functionality, on clicking the button, the to-do typed in the input box is added to the to-dos state. This todos is an array which contains all the to-dos.
- [ ] Add a component to render all the to-dos.

## Iteration 2

- [ ] Add a `bin` icon on the todo item, upon clicking it will delete the item from the todos array.
- [ ] Add an icon to cross the to-do item.  Which marks that the item is completed.
- [ ] Add an icon on click, changes color, which marks the to-do item is an important one.

## Iteration 3

- [ ] Add the ability to persist the to-dos ( use local Storage to save the to-dos, so that the to-dos will not get removed on page load)
- [ ] Themify the todos, day/night using context.
